### PR TITLE
Design system workflow card

### LINKED ISSUE #622: Determinate progress bar
Katy noted that the CDE took a while to load in the sample data. Progress indicators for overall apps are needed. Bruce mentioned that development may be able to return a percentage. I also need to look into the subtle flashing block loading UI: This is a super common modern app loading pattern.

image

### PR DESCRIPTION
**Pull request by edlu77**
#712

- Uses determinate progress bar #622

### CODE REVIEW

**Comment by edlu77** [comment]
@LibbyUX Please review and let me know if everything looks good. I've added a progress bar to the data and color map upload cards in the create vis page, so you can test that out as well.

**Review by LibbyUX — COMMENTED** [review]
Thank you so much @edlu77!! This is looking and feeling so good!

Just a few, hopefully, small requests: 
- For #731 - Is it possible to add a hover state for the icon button on the left side? This whole interaction feels amazing, great work!
- I can't read the tooltips at the moment - The workflow card text appears above it
- Our inputs/selects have been a moving target this year but we are so close to finalized. I see that in the preview, the number input field has space between the label and the input text. Is it possible to reduce this space to 0 and align it as specified?
  - I am working to use [Material Design's text field component framework](https://m3.material.io/components/text-fields/specs) for all selects and inputs in a new component being called "[Text field v2](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/HRA-Design-System-Repository?node-id=6542-24444&t=LJjdVuvcZEg9txVF-4)" in the Design System Repo. It's nearly identical to what was originally specified, but it is more usable in Figma. It also removes the size options, as that was not necessary and goes against what Angular and Material are doing. I will submit this update soon for our design system.

image

image


This looks and feels fantastic, thank you for all of your work on this flow, @edlu77!

**Comment by LibbyUX** [comment]
Also @edlu77 I just want to mention that the progress bar is exquisite!!! Thank you!

**Comment by edlu77** [comment]
@LibbyUX A lot of these issues are addressed in PR #773, which has the updated Delete File Button component and updates to color and styling in the app. It would probably make sense to import some of those changes here though.

**Comment by LibbyUX** [comment]
@edlu77, thanks for pointing me in the right direction for #773. The delete button hover state and the tooltip cards look great over there.

Also, please disregard anything about the text field inputs/selects at the moment! I will submit a design system update when this is ready, so it's irrelevant for this review right now.

Per our conversation just now at my desk, I'll wait for you to ping me when this one is ready for review again!

Thanks so much for everything!

**Review by axdanbol — APPROVED** [review]

**Pull request closed without merging**
