### PR TITLE
Cde landing page updates

### PR DESCRIPTION
**Pull request by edlu77**
#470

### CODE REVIEW

**Comment by bherr2** [comment]
@edlu77 pull from develop and fix the footer conflicts (the old cde-ui footer component should be removed)

**Review by bherr2 — APPROVED** [review]
Once @LibbyUX signs off, the code looks fine, so I'll merge once she approves.

**Comment by LibbyUX** [comment]
> Once @LibbyUX signs off, the code looks fine, so I'll merge once she approves.

@bherr2 & @edlu77 - This is great! Thanks so much!

**Review by bherr2 — APPROVED** [review]

**Comment by LibbyUX** [comment]
Hey @bherr2 & @edlu77 - I just noticed something that caught my eye:

The footer is not centered in this preview: https://667ec9f250c3bc30798726e9--hra-ui.netlify.app/apps/cde-ui/

image

**Comment by LibbyUX** [comment]
I updated the +1920px node in Figma so it stays centered when the width is larger than 1920px: https://www.figma.com/design/G0xVFFsAAnBwzHd8PtQEeb/Cell-Distance-Explorer?node-id=2147-11964&t=6a8Dh3qYfZTLUTYa-4

I will work on a more intuitive/responsive solution for our design system footer, as well, so we can move away from 9 different breakpoints for all the components

**Review by LibbyUX — COMMENTED** [review]
I just need the footer content centered and this should be good to go. Thanks so much!

See https://github.com/hubmapconsortium/hra-ui/pull/484#issuecomment-2197217702 &  https://github.com/hubmapconsortium/hra-ui/issues/470#issuecomment-2197274683 

Preview:
image

Current production:
image

**Pull request merged**
