### PR TITLE
Cde visualization app updates

### PR DESCRIPTION
**Pull request by edlu77**
#499 (excluding histogram styles)

### CODE REVIEW

**Review by LibbyUX — COMMENTED** [review]
Visually we are there 100% on removing the corner radiuses, the strokes/borders, and the padding spacing! Amazing work @edlu77 !!

Iterative questions:
- Is it possible to make the containers more responsive?
  - On zoom, the header nav controls are pushed further to the right, but it would be amazing if they could squish in to the min width? Or are we already there?
  - Is it possible to make the vertical height behavior of the visualization module & histogram component behave more similarly to the spec?
  
This is new territory for me, so don't hesitate to let me know what is/isn't possible. I always zoom in/out on our interfaces to create UI annotation images with legible fonts at dimensions of 2816x1816. The EUI is a great example of how zooming in keeps everything contained in the browser window!

**Comment by edlu77** [comment]
@LibbyUX All the styles on the page should be pretty close to the spec now. Still some additional tweaks needed for responsiveness but it's getting close!

**Review by LibbyUX — DISMISSED** [review]
It's looking so good! Shoutout @edlu77 for REAL! Amazing job on this level of detail. These buttons look sooo good right aligned with the same padding in separate components! Thank you!!! 

image

I only caught one area for improvement and it is low priority. There is a slight jumpiness to the fonts between a certain breakpoint. We aren't optimized for this breakpoint anyway, but I found it interesting to see this slight jumpy text interaction while resizing my Google Chrome browser window!

D2BFD953-79B3-4F57-A03E-50B34738B4EE


I approve of this PR - thank you so much @edlu77 for working this. Our CDE is looking ultra fresh and user friendly!

**Comment by edlu77** [comment]
@LibbyUX I see what happened here. The letter spacing isn't consistent between the different breakpoints...

I couldn't find the letter spacing value on Figma, what is it supposed to be?

**Comment by LibbyUX** [comment]
@edlu77 nice catch! The letter spacing should be 0px, but we might need to iterate. Can you please let me know when the preview is updated, so that I can verify that it's good at 0px online?

Attaching our [UI Typography Style Sheet](https://www.figma.com/design/gQEMLugLjweDvbsNNUVffD/Design-System-Repository?node-id=3739-15606&t=WxpTpwlK0zgkVP8O-4) too! Talk soon!

**Review by axdanbol — APPROVED** [review]

**Pull request merged**
