### PR TITLE
24 hr event page updates

### PR DESCRIPTION
**Pull request by edlu77**

### CODE REVIEW

**Comment by LibbyUX** [comment]
Hi @edlu77, I have a request for this UI now that I see it here:
https://67330a328fc5ee75aae666e2--hra-ui.netlify.app/apps/humanatlas.io/events/2024-24h/

Is it possible to remove the borders for the images? I believe it would look better and be more on brand without the borders/strokes around the circular images. 

image

**Comment by edlu77** [comment]
@LibbyUX Border has been removed! Let me know if anything else comes up.

**Comment by edlu77** [comment]
@LibbyUX Link to new preview: https://673397be06b89f20f5809721--hra-ui.netlify.app/apps/humanatlas.io/events/2024-24h/

(For future reference you can access the page if you add "events/2024-24h" at the end of the preview url)

**Comment by LibbyUX** [comment]
@edlu77 Thanks so much - It looks great on my end! This design/build is likely going to be more iterative with the content still being situated. I emailed Katy/team with the preview link and image board tonight making sure to CC you. Talk soon and have a lovely evening!

**Pull request merged**
