### PR TITLE
Update tools overview

### PR DESCRIPTION
**Pull request by bhushankhope**
work in progress

### CODE REVIEW

**Comment by LibbyUX** [comment]
Hi @bhushankhope, thanks for getting this started!

This is ready to be completed and design progress updates are captured on the relevant issue: https://github.com/hubmapconsortium/hra-ui/issues/461

Thanks for everything!

**Review by LibbyUX — CHANGES_REQUESTED** [review]
Is there a new preview link I should be reviewing? This is what I see in [Figma](https://www.figma.com/design/TtpcTcJNLCxAQiNb2wOA2s/Human-Reference-Atlas%3A-4th-(v1.3)---7th-(v2.1)?node-id=5487-30426&t=KJpij81pFMif3bB3-4) vs production preview. Thanks so much for knocking this out!!

image

**Comment by bhushankhope** [comment]
@LibbyUX [preview link](https://github.com/hubmapconsortium/hra-ui/pull/464#issuecomment-2176088270)

**Comment by LibbyUX** [comment]
Whoops, I may have hit the wrong button just now, lol! I previewed the most recent update @bhushankhope and I approve!

**Review by axdanbol — APPROVED** [review]

**Pull request merged**
